version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm install
      - run: bash ./build.sh
      - run: rm dist/.gitkeep
      - run: zip -r dist.zip dist/

      - persist_to_workspace:
          root: ./
          paths: 
            - dist.zip

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ~/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ~/artifacts/dist.zip

            
workflows:
  version: 2
  main:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/