name: detect non-inclusive

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: true
